// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: token_holder.proto

package models

import (
	context "context"
	fmt "fmt"
	
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	math "math"

	gorm2 "github.com/infobloxopen/atlas-app-toolkit/gorm"
	errors1 "github.com/infobloxopen/protoc-gen-gorm/errors"
	gorm1 "github.com/jinzhu/gorm"
	field_mask1 "google.golang.org/genproto/protobuf/field_mask"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = math.Inf

type TokenHolderORM struct {
	HolderAddress        string `gorm:"primary_key"`
	TokenContractAddress string `gorm:"primary_key;index:token_holders_idx_token_contract_address"`
	Value                string
	ValueDecimal         float64 `gorm:"index:token_holders_idx_value_decimal"`
}

// TableName overrides the default tablename generated by GORM
func (TokenHolderORM) TableName() string {
	return "token_holders"
}

// ToORM runs the BeforeToORM hook if present, converts the fields of this
// object to ORM format, runs the AfterToORM hook, then returns the ORM object
func (m *TokenHolder) ToORM(ctx context.Context) (TokenHolderORM, error) {
	to := TokenHolderORM{}
	var err error
	if prehook, ok := interface{}(m).(TokenHolderWithBeforeToORM); ok {
		if err = prehook.BeforeToORM(ctx, &to); err != nil {
			return to, err
		}
	}
	to.TokenContractAddress = m.TokenContractAddress
	to.HolderAddress = m.HolderAddress
	to.Value = m.Value
	to.ValueDecimal = m.ValueDecimal
	if posthook, ok := interface{}(m).(TokenHolderWithAfterToORM); ok {
		err = posthook.AfterToORM(ctx, &to)
	}
	return to, err
}

// ToPB runs the BeforeToPB hook if present, converts the fields of this
// object to PB format, runs the AfterToPB hook, then returns the PB object
func (m *TokenHolderORM) ToPB(ctx context.Context) (TokenHolder, error) {
	to := TokenHolder{}
	var err error
	if prehook, ok := interface{}(m).(TokenHolderWithBeforeToPB); ok {
		if err = prehook.BeforeToPB(ctx, &to); err != nil {
			return to, err
		}
	}
	to.TokenContractAddress = m.TokenContractAddress
	to.HolderAddress = m.HolderAddress
	to.Value = m.Value
	to.ValueDecimal = m.ValueDecimal
	if posthook, ok := interface{}(m).(TokenHolderWithAfterToPB); ok {
		err = posthook.AfterToPB(ctx, &to)
	}
	return to, err
}

// The following are interfaces you can implement for special behavior during ORM/PB conversions
// of type TokenHolder the arg will be the target, the caller the one being converted from

// TokenHolderBeforeToORM called before default ToORM code
type TokenHolderWithBeforeToORM interface {
	BeforeToORM(context.Context, *TokenHolderORM) error
}

// TokenHolderAfterToORM called after default ToORM code
type TokenHolderWithAfterToORM interface {
	AfterToORM(context.Context, *TokenHolderORM) error
}

// TokenHolderBeforeToPB called before default ToPB code
type TokenHolderWithBeforeToPB interface {
	BeforeToPB(context.Context, *TokenHolder) error
}

// TokenHolderAfterToPB called after default ToPB code
type TokenHolderWithAfterToPB interface {
	AfterToPB(context.Context, *TokenHolder) error
}

// DefaultCreateTokenHolder executes a basic gorm create call
func DefaultCreateTokenHolder(ctx context.Context, in *TokenHolder, db *gorm1.DB) (*TokenHolder, error) {
	if in == nil {
		return nil, errors1.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TokenHolderORMWithBeforeCreate_); ok {
		if db, err = hook.BeforeCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	if err = db.Create(&ormObj).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TokenHolderORMWithAfterCreate_); ok {
		if err = hook.AfterCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := ormObj.ToPB(ctx)
	return &pbResponse, err
}

type TokenHolderORMWithBeforeCreate_ interface {
	BeforeCreate_(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type TokenHolderORMWithAfterCreate_ interface {
	AfterCreate_(context.Context, *gorm1.DB) error
}

// DefaultApplyFieldMaskTokenHolder patches an pbObject with patcher according to a field mask.
func DefaultApplyFieldMaskTokenHolder(ctx context.Context, patchee *TokenHolder, patcher *TokenHolder, updateMask *field_mask1.FieldMask, prefix string, db *gorm1.DB) (*TokenHolder, error) {
	if patcher == nil {
		return nil, nil
	} else if patchee == nil {
		return nil, errors1.NilArgumentError
	}
	var err error
	for _, f := range updateMask.Paths {
		if f == prefix+"TokenContractAddress" {
			patchee.TokenContractAddress = patcher.TokenContractAddress
			continue
		}
		if f == prefix+"HolderAddress" {
			patchee.HolderAddress = patcher.HolderAddress
			continue
		}
		if f == prefix+"Value" {
			patchee.Value = patcher.Value
			continue
		}
		if f == prefix+"ValueDecimal" {
			patchee.ValueDecimal = patcher.ValueDecimal
			continue
		}
	}
	if err != nil {
		return nil, err
	}
	return patchee, nil
}

// DefaultListTokenHolder executes a gorm list call
func DefaultListTokenHolder(ctx context.Context, db *gorm1.DB) ([]*TokenHolder, error) {
	in := TokenHolder{}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TokenHolderORMWithBeforeListApplyQuery); ok {
		if db, err = hook.BeforeListApplyQuery(ctx, db); err != nil {
			return nil, err
		}
	}
	db, err = gorm2.ApplyCollectionOperators(ctx, db, &TokenHolderORM{}, &TokenHolder{}, nil, nil, nil, nil)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TokenHolderORMWithBeforeListFind); ok {
		if db, err = hook.BeforeListFind(ctx, db); err != nil {
			return nil, err
		}
	}
	db = db.Where(&ormObj)
	db = db.Order("token_contract_address")
	ormResponse := []TokenHolderORM{}
	if err := db.Find(&ormResponse).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TokenHolderORMWithAfterListFind); ok {
		if err = hook.AfterListFind(ctx, db, &ormResponse); err != nil {
			return nil, err
		}
	}
	pbResponse := []*TokenHolder{}
	for _, responseEntry := range ormResponse {
		temp, err := responseEntry.ToPB(ctx)
		if err != nil {
			return nil, err
		}
		pbResponse = append(pbResponse, &temp)
	}
	return pbResponse, nil
}

type TokenHolderORMWithBeforeListApplyQuery interface {
	BeforeListApplyQuery(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type TokenHolderORMWithBeforeListFind interface {
	BeforeListFind(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type TokenHolderORMWithAfterListFind interface {
	AfterListFind(context.Context, *gorm1.DB, *[]TokenHolderORM) error
}
