// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: token_holder_count_by_token_contract.proto

package models

import (
	context "context"
	fmt "fmt"
	
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	math "math"

	gorm2 "github.com/infobloxopen/atlas-app-toolkit/gorm"
	errors1 "github.com/infobloxopen/protoc-gen-gorm/errors"
	gorm1 "github.com/jinzhu/gorm"
	field_mask1 "google.golang.org/genproto/protobuf/field_mask"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = math.Inf

type TokenHolderCountByTokenContractORM struct {
	Count                uint64
	TokenContractAddress string `gorm:"primary_key"`
}

// TableName overrides the default tablename generated by GORM
func (TokenHolderCountByTokenContractORM) TableName() string {
	return "token_holder_count_by_token_contracts"
}

// ToORM runs the BeforeToORM hook if present, converts the fields of this
// object to ORM format, runs the AfterToORM hook, then returns the ORM object
func (m *TokenHolderCountByTokenContract) ToORM(ctx context.Context) (TokenHolderCountByTokenContractORM, error) {
	to := TokenHolderCountByTokenContractORM{}
	var err error
	if prehook, ok := interface{}(m).(TokenHolderCountByTokenContractWithBeforeToORM); ok {
		if err = prehook.BeforeToORM(ctx, &to); err != nil {
			return to, err
		}
	}
	to.TokenContractAddress = m.TokenContractAddress
	to.Count = m.Count
	if posthook, ok := interface{}(m).(TokenHolderCountByTokenContractWithAfterToORM); ok {
		err = posthook.AfterToORM(ctx, &to)
	}
	return to, err
}

// ToPB runs the BeforeToPB hook if present, converts the fields of this
// object to PB format, runs the AfterToPB hook, then returns the PB object
func (m *TokenHolderCountByTokenContractORM) ToPB(ctx context.Context) (TokenHolderCountByTokenContract, error) {
	to := TokenHolderCountByTokenContract{}
	var err error
	if prehook, ok := interface{}(m).(TokenHolderCountByTokenContractWithBeforeToPB); ok {
		if err = prehook.BeforeToPB(ctx, &to); err != nil {
			return to, err
		}
	}
	to.TokenContractAddress = m.TokenContractAddress
	to.Count = m.Count
	if posthook, ok := interface{}(m).(TokenHolderCountByTokenContractWithAfterToPB); ok {
		err = posthook.AfterToPB(ctx, &to)
	}
	return to, err
}

// The following are interfaces you can implement for special behavior during ORM/PB conversions
// of type TokenHolderCountByTokenContract the arg will be the target, the caller the one being converted from

// TokenHolderCountByTokenContractBeforeToORM called before default ToORM code
type TokenHolderCountByTokenContractWithBeforeToORM interface {
	BeforeToORM(context.Context, *TokenHolderCountByTokenContractORM) error
}

// TokenHolderCountByTokenContractAfterToORM called after default ToORM code
type TokenHolderCountByTokenContractWithAfterToORM interface {
	AfterToORM(context.Context, *TokenHolderCountByTokenContractORM) error
}

// TokenHolderCountByTokenContractBeforeToPB called before default ToPB code
type TokenHolderCountByTokenContractWithBeforeToPB interface {
	BeforeToPB(context.Context, *TokenHolderCountByTokenContract) error
}

// TokenHolderCountByTokenContractAfterToPB called after default ToPB code
type TokenHolderCountByTokenContractWithAfterToPB interface {
	AfterToPB(context.Context, *TokenHolderCountByTokenContract) error
}

// DefaultCreateTokenHolderCountByTokenContract executes a basic gorm create call
func DefaultCreateTokenHolderCountByTokenContract(ctx context.Context, in *TokenHolderCountByTokenContract, db *gorm1.DB) (*TokenHolderCountByTokenContract, error) {
	if in == nil {
		return nil, errors1.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TokenHolderCountByTokenContractORMWithBeforeCreate_); ok {
		if db, err = hook.BeforeCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	if err = db.Create(&ormObj).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TokenHolderCountByTokenContractORMWithAfterCreate_); ok {
		if err = hook.AfterCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := ormObj.ToPB(ctx)
	return &pbResponse, err
}

type TokenHolderCountByTokenContractORMWithBeforeCreate_ interface {
	BeforeCreate_(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type TokenHolderCountByTokenContractORMWithAfterCreate_ interface {
	AfterCreate_(context.Context, *gorm1.DB) error
}

// DefaultApplyFieldMaskTokenHolderCountByTokenContract patches an pbObject with patcher according to a field mask.
func DefaultApplyFieldMaskTokenHolderCountByTokenContract(ctx context.Context, patchee *TokenHolderCountByTokenContract, patcher *TokenHolderCountByTokenContract, updateMask *field_mask1.FieldMask, prefix string, db *gorm1.DB) (*TokenHolderCountByTokenContract, error) {
	if patcher == nil {
		return nil, nil
	} else if patchee == nil {
		return nil, errors1.NilArgumentError
	}
	var err error
	for _, f := range updateMask.Paths {
		if f == prefix+"TokenContractAddress" {
			patchee.TokenContractAddress = patcher.TokenContractAddress
			continue
		}
		if f == prefix+"Count" {
			patchee.Count = patcher.Count
			continue
		}
	}
	if err != nil {
		return nil, err
	}
	return patchee, nil
}

// DefaultListTokenHolderCountByTokenContract executes a gorm list call
func DefaultListTokenHolderCountByTokenContract(ctx context.Context, db *gorm1.DB) ([]*TokenHolderCountByTokenContract, error) {
	in := TokenHolderCountByTokenContract{}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TokenHolderCountByTokenContractORMWithBeforeListApplyQuery); ok {
		if db, err = hook.BeforeListApplyQuery(ctx, db); err != nil {
			return nil, err
		}
	}
	db, err = gorm2.ApplyCollectionOperators(ctx, db, &TokenHolderCountByTokenContractORM{}, &TokenHolderCountByTokenContract{}, nil, nil, nil, nil)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TokenHolderCountByTokenContractORMWithBeforeListFind); ok {
		if db, err = hook.BeforeListFind(ctx, db); err != nil {
			return nil, err
		}
	}
	db = db.Where(&ormObj)
	db = db.Order("token_contract_address")
	ormResponse := []TokenHolderCountByTokenContractORM{}
	if err := db.Find(&ormResponse).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TokenHolderCountByTokenContractORMWithAfterListFind); ok {
		if err = hook.AfterListFind(ctx, db, &ormResponse); err != nil {
			return nil, err
		}
	}
	pbResponse := []*TokenHolderCountByTokenContract{}
	for _, responseEntry := range ormResponse {
		temp, err := responseEntry.ToPB(ctx)
		if err != nil {
			return nil, err
		}
		pbResponse = append(pbResponse, &temp)
	}
	return pbResponse, nil
}

type TokenHolderCountByTokenContractORMWithBeforeListApplyQuery interface {
	BeforeListApplyQuery(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type TokenHolderCountByTokenContractORMWithBeforeListFind interface {
	BeforeListFind(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type TokenHolderCountByTokenContractORMWithAfterListFind interface {
	AfterListFind(context.Context, *gorm1.DB, *[]TokenHolderCountByTokenContractORM) error
}
