// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: token_transfer_count_by_token_contract_index.proto

package models

import (
	context "context"
	fmt "fmt"
	
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	math "math"

	gorm2 "github.com/infobloxopen/atlas-app-toolkit/gorm"
	errors1 "github.com/infobloxopen/protoc-gen-gorm/errors"
	gorm1 "github.com/jinzhu/gorm"
	field_mask1 "google.golang.org/genproto/protobuf/field_mask"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = math.Inf

type TokenTransferCountByTokenContractIndexORM struct {
	BlockNumber     uint64 `gorm:"index:token_transfer_count_by_token_contract_index_idx_block_number"`
	LogIndex        uint64 `gorm:"primary_key"`
	TokenContract   string
	TransactionHash string `gorm:"primary_key"`
}

// TableName overrides the default tablename generated by GORM
func (TokenTransferCountByTokenContractIndexORM) TableName() string {
	return "token_transfer_count_by_token_contract_indices"
}

// ToORM runs the BeforeToORM hook if present, converts the fields of this
// object to ORM format, runs the AfterToORM hook, then returns the ORM object
func (m *TokenTransferCountByTokenContractIndex) ToORM(ctx context.Context) (TokenTransferCountByTokenContractIndexORM, error) {
	to := TokenTransferCountByTokenContractIndexORM{}
	var err error
	if prehook, ok := interface{}(m).(TokenTransferCountByTokenContractIndexWithBeforeToORM); ok {
		if err = prehook.BeforeToORM(ctx, &to); err != nil {
			return to, err
		}
	}
	to.TransactionHash = m.TransactionHash
	to.LogIndex = m.LogIndex
	to.TokenContract = m.TokenContract
	to.BlockNumber = m.BlockNumber
	if posthook, ok := interface{}(m).(TokenTransferCountByTokenContractIndexWithAfterToORM); ok {
		err = posthook.AfterToORM(ctx, &to)
	}
	return to, err
}

// ToPB runs the BeforeToPB hook if present, converts the fields of this
// object to PB format, runs the AfterToPB hook, then returns the PB object
func (m *TokenTransferCountByTokenContractIndexORM) ToPB(ctx context.Context) (TokenTransferCountByTokenContractIndex, error) {
	to := TokenTransferCountByTokenContractIndex{}
	var err error
	if prehook, ok := interface{}(m).(TokenTransferCountByTokenContractIndexWithBeforeToPB); ok {
		if err = prehook.BeforeToPB(ctx, &to); err != nil {
			return to, err
		}
	}
	to.TransactionHash = m.TransactionHash
	to.LogIndex = m.LogIndex
	to.TokenContract = m.TokenContract
	to.BlockNumber = m.BlockNumber
	if posthook, ok := interface{}(m).(TokenTransferCountByTokenContractIndexWithAfterToPB); ok {
		err = posthook.AfterToPB(ctx, &to)
	}
	return to, err
}

// The following are interfaces you can implement for special behavior during ORM/PB conversions
// of type TokenTransferCountByTokenContractIndex the arg will be the target, the caller the one being converted from

// TokenTransferCountByTokenContractIndexBeforeToORM called before default ToORM code
type TokenTransferCountByTokenContractIndexWithBeforeToORM interface {
	BeforeToORM(context.Context, *TokenTransferCountByTokenContractIndexORM) error
}

// TokenTransferCountByTokenContractIndexAfterToORM called after default ToORM code
type TokenTransferCountByTokenContractIndexWithAfterToORM interface {
	AfterToORM(context.Context, *TokenTransferCountByTokenContractIndexORM) error
}

// TokenTransferCountByTokenContractIndexBeforeToPB called before default ToPB code
type TokenTransferCountByTokenContractIndexWithBeforeToPB interface {
	BeforeToPB(context.Context, *TokenTransferCountByTokenContractIndex) error
}

// TokenTransferCountByTokenContractIndexAfterToPB called after default ToPB code
type TokenTransferCountByTokenContractIndexWithAfterToPB interface {
	AfterToPB(context.Context, *TokenTransferCountByTokenContractIndex) error
}

// DefaultCreateTokenTransferCountByTokenContractIndex executes a basic gorm create call
func DefaultCreateTokenTransferCountByTokenContractIndex(ctx context.Context, in *TokenTransferCountByTokenContractIndex, db *gorm1.DB) (*TokenTransferCountByTokenContractIndex, error) {
	if in == nil {
		return nil, errors1.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TokenTransferCountByTokenContractIndexORMWithBeforeCreate_); ok {
		if db, err = hook.BeforeCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	if err = db.Create(&ormObj).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TokenTransferCountByTokenContractIndexORMWithAfterCreate_); ok {
		if err = hook.AfterCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := ormObj.ToPB(ctx)
	return &pbResponse, err
}

type TokenTransferCountByTokenContractIndexORMWithBeforeCreate_ interface {
	BeforeCreate_(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type TokenTransferCountByTokenContractIndexORMWithAfterCreate_ interface {
	AfterCreate_(context.Context, *gorm1.DB) error
}

// DefaultApplyFieldMaskTokenTransferCountByTokenContractIndex patches an pbObject with patcher according to a field mask.
func DefaultApplyFieldMaskTokenTransferCountByTokenContractIndex(ctx context.Context, patchee *TokenTransferCountByTokenContractIndex, patcher *TokenTransferCountByTokenContractIndex, updateMask *field_mask1.FieldMask, prefix string, db *gorm1.DB) (*TokenTransferCountByTokenContractIndex, error) {
	if patcher == nil {
		return nil, nil
	} else if patchee == nil {
		return nil, errors1.NilArgumentError
	}
	var err error
	for _, f := range updateMask.Paths {
		if f == prefix+"TransactionHash" {
			patchee.TransactionHash = patcher.TransactionHash
			continue
		}
		if f == prefix+"LogIndex" {
			patchee.LogIndex = patcher.LogIndex
			continue
		}
		if f == prefix+"TokenContract" {
			patchee.TokenContract = patcher.TokenContract
			continue
		}
		if f == prefix+"BlockNumber" {
			patchee.BlockNumber = patcher.BlockNumber
			continue
		}
	}
	if err != nil {
		return nil, err
	}
	return patchee, nil
}

// DefaultListTokenTransferCountByTokenContractIndex executes a gorm list call
func DefaultListTokenTransferCountByTokenContractIndex(ctx context.Context, db *gorm1.DB) ([]*TokenTransferCountByTokenContractIndex, error) {
	in := TokenTransferCountByTokenContractIndex{}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TokenTransferCountByTokenContractIndexORMWithBeforeListApplyQuery); ok {
		if db, err = hook.BeforeListApplyQuery(ctx, db); err != nil {
			return nil, err
		}
	}
	db, err = gorm2.ApplyCollectionOperators(ctx, db, &TokenTransferCountByTokenContractIndexORM{}, &TokenTransferCountByTokenContractIndex{}, nil, nil, nil, nil)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TokenTransferCountByTokenContractIndexORMWithBeforeListFind); ok {
		if db, err = hook.BeforeListFind(ctx, db); err != nil {
			return nil, err
		}
	}
	db = db.Where(&ormObj)
	db = db.Order("transaction_hash")
	ormResponse := []TokenTransferCountByTokenContractIndexORM{}
	if err := db.Find(&ormResponse).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TokenTransferCountByTokenContractIndexORMWithAfterListFind); ok {
		if err = hook.AfterListFind(ctx, db, &ormResponse); err != nil {
			return nil, err
		}
	}
	pbResponse := []*TokenTransferCountByTokenContractIndex{}
	for _, responseEntry := range ormResponse {
		temp, err := responseEntry.ToPB(ctx)
		if err != nil {
			return nil, err
		}
		pbResponse = append(pbResponse, &temp)
	}
	return pbResponse, nil
}

type TokenTransferCountByTokenContractIndexORMWithBeforeListApplyQuery interface {
	BeforeListApplyQuery(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type TokenTransferCountByTokenContractIndexORMWithBeforeListFind interface {
	BeforeListFind(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type TokenTransferCountByTokenContractIndexORMWithAfterListFind interface {
	AfterListFind(context.Context, *gorm1.DB, *[]TokenTransferCountByTokenContractIndexORM) error
}
