// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: token_transfer.proto

package models

import (
	context "context"
	fmt "fmt"
	
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	math "math"

	gorm2 "github.com/infobloxopen/atlas-app-toolkit/gorm"
	errors1 "github.com/infobloxopen/protoc-gen-gorm/errors"
	gorm1 "github.com/jinzhu/gorm"
	field_mask1 "google.golang.org/genproto/protobuf/field_mask"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = math.Inf

type TokenTransferORM struct {
	BlockNumber          uint64 `gorm:"index:token_transfer_idx_block_number"`
	FromAddress          string `gorm:"index:token_transfer_idx_from_address"`
	LogIndex             int32  `gorm:"primary_key"`
	ToAddress            string `gorm:"index:token_transfer_idx_to_address"`
	TokenContractAddress string `gorm:"index:token_transfer_idx_token_contract_address"`
	TransactionHash      string `gorm:"primary_key"`
	Value                string
	ValueDecimal         float64 `gorm:"index:token_transfer_idx_value_decimal"`
}

// TableName overrides the default tablename generated by GORM
func (TokenTransferORM) TableName() string {
	return "token_transfers"
}

// ToORM runs the BeforeToORM hook if present, converts the fields of this
// object to ORM format, runs the AfterToORM hook, then returns the ORM object
func (m *TokenTransfer) ToORM(ctx context.Context) (TokenTransferORM, error) {
	to := TokenTransferORM{}
	var err error
	if prehook, ok := interface{}(m).(TokenTransferWithBeforeToORM); ok {
		if err = prehook.BeforeToORM(ctx, &to); err != nil {
			return to, err
		}
	}
	to.TokenContractAddress = m.TokenContractAddress
	to.FromAddress = m.FromAddress
	to.ToAddress = m.ToAddress
	to.Value = m.Value
	to.TransactionHash = m.TransactionHash
	to.LogIndex = m.LogIndex
	to.BlockNumber = m.BlockNumber
	to.ValueDecimal = m.ValueDecimal
	if posthook, ok := interface{}(m).(TokenTransferWithAfterToORM); ok {
		err = posthook.AfterToORM(ctx, &to)
	}
	return to, err
}

// ToPB runs the BeforeToPB hook if present, converts the fields of this
// object to PB format, runs the AfterToPB hook, then returns the PB object
func (m *TokenTransferORM) ToPB(ctx context.Context) (TokenTransfer, error) {
	to := TokenTransfer{}
	var err error
	if prehook, ok := interface{}(m).(TokenTransferWithBeforeToPB); ok {
		if err = prehook.BeforeToPB(ctx, &to); err != nil {
			return to, err
		}
	}
	to.TokenContractAddress = m.TokenContractAddress
	to.FromAddress = m.FromAddress
	to.ToAddress = m.ToAddress
	to.Value = m.Value
	to.TransactionHash = m.TransactionHash
	to.LogIndex = m.LogIndex
	to.BlockNumber = m.BlockNumber
	to.ValueDecimal = m.ValueDecimal
	if posthook, ok := interface{}(m).(TokenTransferWithAfterToPB); ok {
		err = posthook.AfterToPB(ctx, &to)
	}
	return to, err
}

// The following are interfaces you can implement for special behavior during ORM/PB conversions
// of type TokenTransfer the arg will be the target, the caller the one being converted from

// TokenTransferBeforeToORM called before default ToORM code
type TokenTransferWithBeforeToORM interface {
	BeforeToORM(context.Context, *TokenTransferORM) error
}

// TokenTransferAfterToORM called after default ToORM code
type TokenTransferWithAfterToORM interface {
	AfterToORM(context.Context, *TokenTransferORM) error
}

// TokenTransferBeforeToPB called before default ToPB code
type TokenTransferWithBeforeToPB interface {
	BeforeToPB(context.Context, *TokenTransfer) error
}

// TokenTransferAfterToPB called after default ToPB code
type TokenTransferWithAfterToPB interface {
	AfterToPB(context.Context, *TokenTransfer) error
}

// DefaultCreateTokenTransfer executes a basic gorm create call
func DefaultCreateTokenTransfer(ctx context.Context, in *TokenTransfer, db *gorm1.DB) (*TokenTransfer, error) {
	if in == nil {
		return nil, errors1.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TokenTransferORMWithBeforeCreate_); ok {
		if db, err = hook.BeforeCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	if err = db.Create(&ormObj).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TokenTransferORMWithAfterCreate_); ok {
		if err = hook.AfterCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := ormObj.ToPB(ctx)
	return &pbResponse, err
}

type TokenTransferORMWithBeforeCreate_ interface {
	BeforeCreate_(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type TokenTransferORMWithAfterCreate_ interface {
	AfterCreate_(context.Context, *gorm1.DB) error
}

// DefaultApplyFieldMaskTokenTransfer patches an pbObject with patcher according to a field mask.
func DefaultApplyFieldMaskTokenTransfer(ctx context.Context, patchee *TokenTransfer, patcher *TokenTransfer, updateMask *field_mask1.FieldMask, prefix string, db *gorm1.DB) (*TokenTransfer, error) {
	if patcher == nil {
		return nil, nil
	} else if patchee == nil {
		return nil, errors1.NilArgumentError
	}
	var err error
	for _, f := range updateMask.Paths {
		if f == prefix+"TokenContractAddress" {
			patchee.TokenContractAddress = patcher.TokenContractAddress
			continue
		}
		if f == prefix+"FromAddress" {
			patchee.FromAddress = patcher.FromAddress
			continue
		}
		if f == prefix+"ToAddress" {
			patchee.ToAddress = patcher.ToAddress
			continue
		}
		if f == prefix+"Value" {
			patchee.Value = patcher.Value
			continue
		}
		if f == prefix+"TransactionHash" {
			patchee.TransactionHash = patcher.TransactionHash
			continue
		}
		if f == prefix+"LogIndex" {
			patchee.LogIndex = patcher.LogIndex
			continue
		}
		if f == prefix+"BlockNumber" {
			patchee.BlockNumber = patcher.BlockNumber
			continue
		}
		if f == prefix+"ValueDecimal" {
			patchee.ValueDecimal = patcher.ValueDecimal
			continue
		}
	}
	if err != nil {
		return nil, err
	}
	return patchee, nil
}

// DefaultListTokenTransfer executes a gorm list call
func DefaultListTokenTransfer(ctx context.Context, db *gorm1.DB) ([]*TokenTransfer, error) {
	in := TokenTransfer{}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TokenTransferORMWithBeforeListApplyQuery); ok {
		if db, err = hook.BeforeListApplyQuery(ctx, db); err != nil {
			return nil, err
		}
	}
	db, err = gorm2.ApplyCollectionOperators(ctx, db, &TokenTransferORM{}, &TokenTransfer{}, nil, nil, nil, nil)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TokenTransferORMWithBeforeListFind); ok {
		if db, err = hook.BeforeListFind(ctx, db); err != nil {
			return nil, err
		}
	}
	db = db.Where(&ormObj)
	db = db.Order("transaction_hash")
	ormResponse := []TokenTransferORM{}
	if err := db.Find(&ormResponse).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TokenTransferORMWithAfterListFind); ok {
		if err = hook.AfterListFind(ctx, db, &ormResponse); err != nil {
			return nil, err
		}
	}
	pbResponse := []*TokenTransfer{}
	for _, responseEntry := range ormResponse {
		temp, err := responseEntry.ToPB(ctx)
		if err != nil {
			return nil, err
		}
		pbResponse = append(pbResponse, &temp)
	}
	return pbResponse, nil
}

type TokenTransferORMWithBeforeListApplyQuery interface {
	BeforeListApplyQuery(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type TokenTransferORMWithBeforeListFind interface {
	BeforeListFind(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type TokenTransferORMWithAfterListFind interface {
	AfterListFind(context.Context, *gorm1.DB, *[]TokenTransferORM) error
}
