// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: transaction_internal_count_by_address.proto

package models

import (
	context "context"
	fmt "fmt"
	
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	math "math"

	gorm2 "github.com/infobloxopen/atlas-app-toolkit/gorm"
	errors1 "github.com/infobloxopen/protoc-gen-gorm/errors"
	gorm1 "github.com/jinzhu/gorm"
	field_mask1 "google.golang.org/genproto/protobuf/field_mask"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = math.Inf

type TransactionInternalCountByAddressORM struct {
	Address         string `gorm:"primary_key"`
	Count           uint64
	LogIndex        uint64
	TransactionHash string
}

// TableName overrides the default tablename generated by GORM
func (TransactionInternalCountByAddressORM) TableName() string {
	return "transaction_internal_count_by_addresses"
}

// ToORM runs the BeforeToORM hook if present, converts the fields of this
// object to ORM format, runs the AfterToORM hook, then returns the ORM object
func (m *TransactionInternalCountByAddress) ToORM(ctx context.Context) (TransactionInternalCountByAddressORM, error) {
	to := TransactionInternalCountByAddressORM{}
	var err error
	if prehook, ok := interface{}(m).(TransactionInternalCountByAddressWithBeforeToORM); ok {
		if err = prehook.BeforeToORM(ctx, &to); err != nil {
			return to, err
		}
	}
	to.TransactionHash = m.TransactionHash
	to.LogIndex = m.LogIndex
	to.Address = m.Address
	to.Count = m.Count
	if posthook, ok := interface{}(m).(TransactionInternalCountByAddressWithAfterToORM); ok {
		err = posthook.AfterToORM(ctx, &to)
	}
	return to, err
}

// ToPB runs the BeforeToPB hook if present, converts the fields of this
// object to PB format, runs the AfterToPB hook, then returns the PB object
func (m *TransactionInternalCountByAddressORM) ToPB(ctx context.Context) (TransactionInternalCountByAddress, error) {
	to := TransactionInternalCountByAddress{}
	var err error
	if prehook, ok := interface{}(m).(TransactionInternalCountByAddressWithBeforeToPB); ok {
		if err = prehook.BeforeToPB(ctx, &to); err != nil {
			return to, err
		}
	}
	to.TransactionHash = m.TransactionHash
	to.LogIndex = m.LogIndex
	to.Address = m.Address
	to.Count = m.Count
	if posthook, ok := interface{}(m).(TransactionInternalCountByAddressWithAfterToPB); ok {
		err = posthook.AfterToPB(ctx, &to)
	}
	return to, err
}

// The following are interfaces you can implement for special behavior during ORM/PB conversions
// of type TransactionInternalCountByAddress the arg will be the target, the caller the one being converted from

// TransactionInternalCountByAddressBeforeToORM called before default ToORM code
type TransactionInternalCountByAddressWithBeforeToORM interface {
	BeforeToORM(context.Context, *TransactionInternalCountByAddressORM) error
}

// TransactionInternalCountByAddressAfterToORM called after default ToORM code
type TransactionInternalCountByAddressWithAfterToORM interface {
	AfterToORM(context.Context, *TransactionInternalCountByAddressORM) error
}

// TransactionInternalCountByAddressBeforeToPB called before default ToPB code
type TransactionInternalCountByAddressWithBeforeToPB interface {
	BeforeToPB(context.Context, *TransactionInternalCountByAddress) error
}

// TransactionInternalCountByAddressAfterToPB called after default ToPB code
type TransactionInternalCountByAddressWithAfterToPB interface {
	AfterToPB(context.Context, *TransactionInternalCountByAddress) error
}

// DefaultCreateTransactionInternalCountByAddress executes a basic gorm create call
func DefaultCreateTransactionInternalCountByAddress(ctx context.Context, in *TransactionInternalCountByAddress, db *gorm1.DB) (*TransactionInternalCountByAddress, error) {
	if in == nil {
		return nil, errors1.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TransactionInternalCountByAddressORMWithBeforeCreate_); ok {
		if db, err = hook.BeforeCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	if err = db.Create(&ormObj).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TransactionInternalCountByAddressORMWithAfterCreate_); ok {
		if err = hook.AfterCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := ormObj.ToPB(ctx)
	return &pbResponse, err
}

type TransactionInternalCountByAddressORMWithBeforeCreate_ interface {
	BeforeCreate_(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type TransactionInternalCountByAddressORMWithAfterCreate_ interface {
	AfterCreate_(context.Context, *gorm1.DB) error
}

// DefaultApplyFieldMaskTransactionInternalCountByAddress patches an pbObject with patcher according to a field mask.
func DefaultApplyFieldMaskTransactionInternalCountByAddress(ctx context.Context, patchee *TransactionInternalCountByAddress, patcher *TransactionInternalCountByAddress, updateMask *field_mask1.FieldMask, prefix string, db *gorm1.DB) (*TransactionInternalCountByAddress, error) {
	if patcher == nil {
		return nil, nil
	} else if patchee == nil {
		return nil, errors1.NilArgumentError
	}
	var err error
	for _, f := range updateMask.Paths {
		if f == prefix+"TransactionHash" {
			patchee.TransactionHash = patcher.TransactionHash
			continue
		}
		if f == prefix+"LogIndex" {
			patchee.LogIndex = patcher.LogIndex
			continue
		}
		if f == prefix+"Address" {
			patchee.Address = patcher.Address
			continue
		}
		if f == prefix+"Count" {
			patchee.Count = patcher.Count
			continue
		}
	}
	if err != nil {
		return nil, err
	}
	return patchee, nil
}

// DefaultListTransactionInternalCountByAddress executes a gorm list call
func DefaultListTransactionInternalCountByAddress(ctx context.Context, db *gorm1.DB) ([]*TransactionInternalCountByAddress, error) {
	in := TransactionInternalCountByAddress{}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TransactionInternalCountByAddressORMWithBeforeListApplyQuery); ok {
		if db, err = hook.BeforeListApplyQuery(ctx, db); err != nil {
			return nil, err
		}
	}
	db, err = gorm2.ApplyCollectionOperators(ctx, db, &TransactionInternalCountByAddressORM{}, &TransactionInternalCountByAddress{}, nil, nil, nil, nil)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TransactionInternalCountByAddressORMWithBeforeListFind); ok {
		if db, err = hook.BeforeListFind(ctx, db); err != nil {
			return nil, err
		}
	}
	db = db.Where(&ormObj)
	db = db.Order("address")
	ormResponse := []TransactionInternalCountByAddressORM{}
	if err := db.Find(&ormResponse).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TransactionInternalCountByAddressORMWithAfterListFind); ok {
		if err = hook.AfterListFind(ctx, db, &ormResponse); err != nil {
			return nil, err
		}
	}
	pbResponse := []*TransactionInternalCountByAddress{}
	for _, responseEntry := range ormResponse {
		temp, err := responseEntry.ToPB(ctx)
		if err != nil {
			return nil, err
		}
		pbResponse = append(pbResponse, &temp)
	}
	return pbResponse, nil
}

type TransactionInternalCountByAddressORMWithBeforeListApplyQuery interface {
	BeforeListApplyQuery(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type TransactionInternalCountByAddressORMWithBeforeListFind interface {
	BeforeListFind(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type TransactionInternalCountByAddressORMWithAfterListFind interface {
	AfterListFind(context.Context, *gorm1.DB, *[]TransactionInternalCountByAddressORM) error
}
