// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: transaction_token_transfer_count_index.proto

package models

import (
	context "context"
	fmt "fmt"
	
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	math "math"

	gorm2 "github.com/infobloxopen/atlas-app-toolkit/gorm"
	errors1 "github.com/infobloxopen/protoc-gen-gorm/errors"
	gorm1 "github.com/jinzhu/gorm"
	field_mask1 "google.golang.org/genproto/protobuf/field_mask"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = math.Inf

type TransactionTokenTransferCountIndexORM struct {
	LogIndex        int32  `gorm:"primary_key"`
	TransactionHash string `gorm:"primary_key"`
}

// TableName overrides the default tablename generated by GORM
func (TransactionTokenTransferCountIndexORM) TableName() string {
	return "transaction_token_transfer_count_indices"
}

// ToORM runs the BeforeToORM hook if present, converts the fields of this
// object to ORM format, runs the AfterToORM hook, then returns the ORM object
func (m *TransactionTokenTransferCountIndex) ToORM(ctx context.Context) (TransactionTokenTransferCountIndexORM, error) {
	to := TransactionTokenTransferCountIndexORM{}
	var err error
	if prehook, ok := interface{}(m).(TransactionTokenTransferCountIndexWithBeforeToORM); ok {
		if err = prehook.BeforeToORM(ctx, &to); err != nil {
			return to, err
		}
	}
	to.TransactionHash = m.TransactionHash
	to.LogIndex = m.LogIndex
	if posthook, ok := interface{}(m).(TransactionTokenTransferCountIndexWithAfterToORM); ok {
		err = posthook.AfterToORM(ctx, &to)
	}
	return to, err
}

// ToPB runs the BeforeToPB hook if present, converts the fields of this
// object to PB format, runs the AfterToPB hook, then returns the PB object
func (m *TransactionTokenTransferCountIndexORM) ToPB(ctx context.Context) (TransactionTokenTransferCountIndex, error) {
	to := TransactionTokenTransferCountIndex{}
	var err error
	if prehook, ok := interface{}(m).(TransactionTokenTransferCountIndexWithBeforeToPB); ok {
		if err = prehook.BeforeToPB(ctx, &to); err != nil {
			return to, err
		}
	}
	to.TransactionHash = m.TransactionHash
	to.LogIndex = m.LogIndex
	if posthook, ok := interface{}(m).(TransactionTokenTransferCountIndexWithAfterToPB); ok {
		err = posthook.AfterToPB(ctx, &to)
	}
	return to, err
}

// The following are interfaces you can implement for special behavior during ORM/PB conversions
// of type TransactionTokenTransferCountIndex the arg will be the target, the caller the one being converted from

// TransactionTokenTransferCountIndexBeforeToORM called before default ToORM code
type TransactionTokenTransferCountIndexWithBeforeToORM interface {
	BeforeToORM(context.Context, *TransactionTokenTransferCountIndexORM) error
}

// TransactionTokenTransferCountIndexAfterToORM called after default ToORM code
type TransactionTokenTransferCountIndexWithAfterToORM interface {
	AfterToORM(context.Context, *TransactionTokenTransferCountIndexORM) error
}

// TransactionTokenTransferCountIndexBeforeToPB called before default ToPB code
type TransactionTokenTransferCountIndexWithBeforeToPB interface {
	BeforeToPB(context.Context, *TransactionTokenTransferCountIndex) error
}

// TransactionTokenTransferCountIndexAfterToPB called after default ToPB code
type TransactionTokenTransferCountIndexWithAfterToPB interface {
	AfterToPB(context.Context, *TransactionTokenTransferCountIndex) error
}

// DefaultCreateTransactionTokenTransferCountIndex executes a basic gorm create call
func DefaultCreateTransactionTokenTransferCountIndex(ctx context.Context, in *TransactionTokenTransferCountIndex, db *gorm1.DB) (*TransactionTokenTransferCountIndex, error) {
	if in == nil {
		return nil, errors1.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TransactionTokenTransferCountIndexORMWithBeforeCreate_); ok {
		if db, err = hook.BeforeCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	if err = db.Create(&ormObj).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TransactionTokenTransferCountIndexORMWithAfterCreate_); ok {
		if err = hook.AfterCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := ormObj.ToPB(ctx)
	return &pbResponse, err
}

type TransactionTokenTransferCountIndexORMWithBeforeCreate_ interface {
	BeforeCreate_(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type TransactionTokenTransferCountIndexORMWithAfterCreate_ interface {
	AfterCreate_(context.Context, *gorm1.DB) error
}

// DefaultApplyFieldMaskTransactionTokenTransferCountIndex patches an pbObject with patcher according to a field mask.
func DefaultApplyFieldMaskTransactionTokenTransferCountIndex(ctx context.Context, patchee *TransactionTokenTransferCountIndex, patcher *TransactionTokenTransferCountIndex, updateMask *field_mask1.FieldMask, prefix string, db *gorm1.DB) (*TransactionTokenTransferCountIndex, error) {
	if patcher == nil {
		return nil, nil
	} else if patchee == nil {
		return nil, errors1.NilArgumentError
	}
	var err error
	for _, f := range updateMask.Paths {
		if f == prefix+"TransactionHash" {
			patchee.TransactionHash = patcher.TransactionHash
			continue
		}
		if f == prefix+"LogIndex" {
			patchee.LogIndex = patcher.LogIndex
			continue
		}
	}
	if err != nil {
		return nil, err
	}
	return patchee, nil
}

// DefaultListTransactionTokenTransferCountIndex executes a gorm list call
func DefaultListTransactionTokenTransferCountIndex(ctx context.Context, db *gorm1.DB) ([]*TransactionTokenTransferCountIndex, error) {
	in := TransactionTokenTransferCountIndex{}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TransactionTokenTransferCountIndexORMWithBeforeListApplyQuery); ok {
		if db, err = hook.BeforeListApplyQuery(ctx, db); err != nil {
			return nil, err
		}
	}
	db, err = gorm2.ApplyCollectionOperators(ctx, db, &TransactionTokenTransferCountIndexORM{}, &TransactionTokenTransferCountIndex{}, nil, nil, nil, nil)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TransactionTokenTransferCountIndexORMWithBeforeListFind); ok {
		if db, err = hook.BeforeListFind(ctx, db); err != nil {
			return nil, err
		}
	}
	db = db.Where(&ormObj)
	db = db.Order("transaction_hash")
	ormResponse := []TransactionTokenTransferCountIndexORM{}
	if err := db.Find(&ormResponse).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TransactionTokenTransferCountIndexORMWithAfterListFind); ok {
		if err = hook.AfterListFind(ctx, db, &ormResponse); err != nil {
			return nil, err
		}
	}
	pbResponse := []*TransactionTokenTransferCountIndex{}
	for _, responseEntry := range ormResponse {
		temp, err := responseEntry.ToPB(ctx)
		if err != nil {
			return nil, err
		}
		pbResponse = append(pbResponse, &temp)
	}
	return pbResponse, nil
}

type TransactionTokenTransferCountIndexORMWithBeforeListApplyQuery interface {
	BeforeListApplyQuery(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type TransactionTokenTransferCountIndexORMWithBeforeListFind interface {
	BeforeListFind(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type TransactionTokenTransferCountIndexORMWithAfterListFind interface {
	AfterListFind(context.Context, *gorm1.DB, *[]TransactionTokenTransferCountIndexORM) error
}
