// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: transaction_ws.proto

package models

import (
	context "context"
	fmt "fmt"
	
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	math "math"

	gorm2 "github.com/infobloxopen/atlas-app-toolkit/gorm"
	errors1 "github.com/infobloxopen/protoc-gen-gorm/errors"
	gorm1 "github.com/jinzhu/gorm"
	field_mask1 "google.golang.org/genproto/protobuf/field_mask"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = math.Inf

type TransactionWebsocketIndexORM struct {
	Hash string `gorm:"primary_key"`
}

// TableName overrides the default tablename generated by GORM
func (TransactionWebsocketIndexORM) TableName() string {
	return "transaction_websocket_indices"
}

// ToORM runs the BeforeToORM hook if present, converts the fields of this
// object to ORM format, runs the AfterToORM hook, then returns the ORM object
func (m *TransactionWebsocketIndex) ToORM(ctx context.Context) (TransactionWebsocketIndexORM, error) {
	to := TransactionWebsocketIndexORM{}
	var err error
	if prehook, ok := interface{}(m).(TransactionWebsocketIndexWithBeforeToORM); ok {
		if err = prehook.BeforeToORM(ctx, &to); err != nil {
			return to, err
		}
	}
	to.Hash = m.Hash
	if posthook, ok := interface{}(m).(TransactionWebsocketIndexWithAfterToORM); ok {
		err = posthook.AfterToORM(ctx, &to)
	}
	return to, err
}

// ToPB runs the BeforeToPB hook if present, converts the fields of this
// object to PB format, runs the AfterToPB hook, then returns the PB object
func (m *TransactionWebsocketIndexORM) ToPB(ctx context.Context) (TransactionWebsocketIndex, error) {
	to := TransactionWebsocketIndex{}
	var err error
	if prehook, ok := interface{}(m).(TransactionWebsocketIndexWithBeforeToPB); ok {
		if err = prehook.BeforeToPB(ctx, &to); err != nil {
			return to, err
		}
	}
	to.Hash = m.Hash
	if posthook, ok := interface{}(m).(TransactionWebsocketIndexWithAfterToPB); ok {
		err = posthook.AfterToPB(ctx, &to)
	}
	return to, err
}

// The following are interfaces you can implement for special behavior during ORM/PB conversions
// of type TransactionWebsocketIndex the arg will be the target, the caller the one being converted from

// TransactionWebsocketIndexBeforeToORM called before default ToORM code
type TransactionWebsocketIndexWithBeforeToORM interface {
	BeforeToORM(context.Context, *TransactionWebsocketIndexORM) error
}

// TransactionWebsocketIndexAfterToORM called after default ToORM code
type TransactionWebsocketIndexWithAfterToORM interface {
	AfterToORM(context.Context, *TransactionWebsocketIndexORM) error
}

// TransactionWebsocketIndexBeforeToPB called before default ToPB code
type TransactionWebsocketIndexWithBeforeToPB interface {
	BeforeToPB(context.Context, *TransactionWebsocketIndex) error
}

// TransactionWebsocketIndexAfterToPB called after default ToPB code
type TransactionWebsocketIndexWithAfterToPB interface {
	AfterToPB(context.Context, *TransactionWebsocketIndex) error
}

// DefaultCreateTransactionWebsocketIndex executes a basic gorm create call
func DefaultCreateTransactionWebsocketIndex(ctx context.Context, in *TransactionWebsocketIndex, db *gorm1.DB) (*TransactionWebsocketIndex, error) {
	if in == nil {
		return nil, errors1.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TransactionWebsocketIndexORMWithBeforeCreate_); ok {
		if db, err = hook.BeforeCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	if err = db.Create(&ormObj).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TransactionWebsocketIndexORMWithAfterCreate_); ok {
		if err = hook.AfterCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := ormObj.ToPB(ctx)
	return &pbResponse, err
}

type TransactionWebsocketIndexORMWithBeforeCreate_ interface {
	BeforeCreate_(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type TransactionWebsocketIndexORMWithAfterCreate_ interface {
	AfterCreate_(context.Context, *gorm1.DB) error
}

// DefaultApplyFieldMaskTransactionWebsocketIndex patches an pbObject with patcher according to a field mask.
func DefaultApplyFieldMaskTransactionWebsocketIndex(ctx context.Context, patchee *TransactionWebsocketIndex, patcher *TransactionWebsocketIndex, updateMask *field_mask1.FieldMask, prefix string, db *gorm1.DB) (*TransactionWebsocketIndex, error) {
	if patcher == nil {
		return nil, nil
	} else if patchee == nil {
		return nil, errors1.NilArgumentError
	}
	var err error
	for _, f := range updateMask.Paths {
		if f == prefix+"Hash" {
			patchee.Hash = patcher.Hash
			continue
		}
	}
	if err != nil {
		return nil, err
	}
	return patchee, nil
}

// DefaultListTransactionWebsocketIndex executes a gorm list call
func DefaultListTransactionWebsocketIndex(ctx context.Context, db *gorm1.DB) ([]*TransactionWebsocketIndex, error) {
	in := TransactionWebsocketIndex{}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TransactionWebsocketIndexORMWithBeforeListApplyQuery); ok {
		if db, err = hook.BeforeListApplyQuery(ctx, db); err != nil {
			return nil, err
		}
	}
	db, err = gorm2.ApplyCollectionOperators(ctx, db, &TransactionWebsocketIndexORM{}, &TransactionWebsocketIndex{}, nil, nil, nil, nil)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TransactionWebsocketIndexORMWithBeforeListFind); ok {
		if db, err = hook.BeforeListFind(ctx, db); err != nil {
			return nil, err
		}
	}
	db = db.Where(&ormObj)
	db = db.Order("hash")
	ormResponse := []TransactionWebsocketIndexORM{}
	if err := db.Find(&ormResponse).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TransactionWebsocketIndexORMWithAfterListFind); ok {
		if err = hook.AfterListFind(ctx, db, &ormResponse); err != nil {
			return nil, err
		}
	}
	pbResponse := []*TransactionWebsocketIndex{}
	for _, responseEntry := range ormResponse {
		temp, err := responseEntry.ToPB(ctx)
		if err != nil {
			return nil, err
		}
		pbResponse = append(pbResponse, &temp)
	}
	return pbResponse, nil
}

type TransactionWebsocketIndexORMWithBeforeListApplyQuery interface {
	BeforeListApplyQuery(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type TransactionWebsocketIndexORMWithBeforeListFind interface {
	BeforeListFind(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type TransactionWebsocketIndexORMWithAfterListFind interface {
	AfterListFind(context.Context, *gorm1.DB, *[]TransactionWebsocketIndexORM) error
}
