// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: transaction_missing.proto

package models

import (
	context "context"
	fmt "fmt"
	
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	math "math"

	gorm2 "github.com/infobloxopen/atlas-app-toolkit/gorm"
	errors1 "github.com/infobloxopen/protoc-gen-gorm/errors"
	gorm1 "github.com/jinzhu/gorm"
	field_mask1 "google.golang.org/genproto/protobuf/field_mask"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = math.Inf

type TransactionMissingORM struct {
	Hash string `gorm:"primary_key"`
}

// TableName overrides the default tablename generated by GORM
func (TransactionMissingORM) TableName() string {
	return "transaction_missings"
}

// ToORM runs the BeforeToORM hook if present, converts the fields of this
// object to ORM format, runs the AfterToORM hook, then returns the ORM object
func (m *TransactionMissing) ToORM(ctx context.Context) (TransactionMissingORM, error) {
	to := TransactionMissingORM{}
	var err error
	if prehook, ok := interface{}(m).(TransactionMissingWithBeforeToORM); ok {
		if err = prehook.BeforeToORM(ctx, &to); err != nil {
			return to, err
		}
	}
	to.Hash = m.Hash
	if posthook, ok := interface{}(m).(TransactionMissingWithAfterToORM); ok {
		err = posthook.AfterToORM(ctx, &to)
	}
	return to, err
}

// ToPB runs the BeforeToPB hook if present, converts the fields of this
// object to PB format, runs the AfterToPB hook, then returns the PB object
func (m *TransactionMissingORM) ToPB(ctx context.Context) (TransactionMissing, error) {
	to := TransactionMissing{}
	var err error
	if prehook, ok := interface{}(m).(TransactionMissingWithBeforeToPB); ok {
		if err = prehook.BeforeToPB(ctx, &to); err != nil {
			return to, err
		}
	}
	to.Hash = m.Hash
	if posthook, ok := interface{}(m).(TransactionMissingWithAfterToPB); ok {
		err = posthook.AfterToPB(ctx, &to)
	}
	return to, err
}

// The following are interfaces you can implement for special behavior during ORM/PB conversions
// of type TransactionMissing the arg will be the target, the caller the one being converted from

// TransactionMissingBeforeToORM called before default ToORM code
type TransactionMissingWithBeforeToORM interface {
	BeforeToORM(context.Context, *TransactionMissingORM) error
}

// TransactionMissingAfterToORM called after default ToORM code
type TransactionMissingWithAfterToORM interface {
	AfterToORM(context.Context, *TransactionMissingORM) error
}

// TransactionMissingBeforeToPB called before default ToPB code
type TransactionMissingWithBeforeToPB interface {
	BeforeToPB(context.Context, *TransactionMissing) error
}

// TransactionMissingAfterToPB called after default ToPB code
type TransactionMissingWithAfterToPB interface {
	AfterToPB(context.Context, *TransactionMissing) error
}

// DefaultCreateTransactionMissing executes a basic gorm create call
func DefaultCreateTransactionMissing(ctx context.Context, in *TransactionMissing, db *gorm1.DB) (*TransactionMissing, error) {
	if in == nil {
		return nil, errors1.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TransactionMissingORMWithBeforeCreate_); ok {
		if db, err = hook.BeforeCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	if err = db.Create(&ormObj).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TransactionMissingORMWithAfterCreate_); ok {
		if err = hook.AfterCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := ormObj.ToPB(ctx)
	return &pbResponse, err
}

type TransactionMissingORMWithBeforeCreate_ interface {
	BeforeCreate_(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type TransactionMissingORMWithAfterCreate_ interface {
	AfterCreate_(context.Context, *gorm1.DB) error
}

// DefaultApplyFieldMaskTransactionMissing patches an pbObject with patcher according to a field mask.
func DefaultApplyFieldMaskTransactionMissing(ctx context.Context, patchee *TransactionMissing, patcher *TransactionMissing, updateMask *field_mask1.FieldMask, prefix string, db *gorm1.DB) (*TransactionMissing, error) {
	if patcher == nil {
		return nil, nil
	} else if patchee == nil {
		return nil, errors1.NilArgumentError
	}
	var err error
	for _, f := range updateMask.Paths {
		if f == prefix+"Hash" {
			patchee.Hash = patcher.Hash
			continue
		}
	}
	if err != nil {
		return nil, err
	}
	return patchee, nil
}

// DefaultListTransactionMissing executes a gorm list call
func DefaultListTransactionMissing(ctx context.Context, db *gorm1.DB) ([]*TransactionMissing, error) {
	in := TransactionMissing{}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TransactionMissingORMWithBeforeListApplyQuery); ok {
		if db, err = hook.BeforeListApplyQuery(ctx, db); err != nil {
			return nil, err
		}
	}
	db, err = gorm2.ApplyCollectionOperators(ctx, db, &TransactionMissingORM{}, &TransactionMissing{}, nil, nil, nil, nil)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TransactionMissingORMWithBeforeListFind); ok {
		if db, err = hook.BeforeListFind(ctx, db); err != nil {
			return nil, err
		}
	}
	db = db.Where(&ormObj)
	db = db.Order("hash")
	ormResponse := []TransactionMissingORM{}
	if err := db.Find(&ormResponse).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TransactionMissingORMWithAfterListFind); ok {
		if err = hook.AfterListFind(ctx, db, &ormResponse); err != nil {
			return nil, err
		}
	}
	pbResponse := []*TransactionMissing{}
	for _, responseEntry := range ormResponse {
		temp, err := responseEntry.ToPB(ctx)
		if err != nil {
			return nil, err
		}
		pbResponse = append(pbResponse, &temp)
	}
	return pbResponse, nil
}

type TransactionMissingORMWithBeforeListApplyQuery interface {
	BeforeListApplyQuery(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type TransactionMissingORMWithBeforeListFind interface {
	BeforeListFind(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type TransactionMissingORMWithAfterListFind interface {
	AfterListFind(context.Context, *gorm1.DB, *[]TransactionMissingORM) error
}
