// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: transaction_count_by_address.proto

package models

import (
	context "context"
	fmt "fmt"
	
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	math "math"

	gorm2 "github.com/infobloxopen/atlas-app-toolkit/gorm"
	errors1 "github.com/infobloxopen/protoc-gen-gorm/errors"
	gorm1 "github.com/jinzhu/gorm"
	field_mask1 "google.golang.org/genproto/protobuf/field_mask"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = math.Inf

type TransactionCountByAddressORM struct {
	Address         string `gorm:"primary_key"`
	Count           uint64 `gorm:"index:transaction_count_by_address_idx_count"`
	TransactionHash string
}

// TableName overrides the default tablename generated by GORM
func (TransactionCountByAddressORM) TableName() string {
	return "transaction_count_by_addresses"
}

// ToORM runs the BeforeToORM hook if present, converts the fields of this
// object to ORM format, runs the AfterToORM hook, then returns the ORM object
func (m *TransactionCountByAddress) ToORM(ctx context.Context) (TransactionCountByAddressORM, error) {
	to := TransactionCountByAddressORM{}
	var err error
	if prehook, ok := interface{}(m).(TransactionCountByAddressWithBeforeToORM); ok {
		if err = prehook.BeforeToORM(ctx, &to); err != nil {
			return to, err
		}
	}
	to.Address = m.Address
	to.TransactionHash = m.TransactionHash
	to.Count = m.Count
	if posthook, ok := interface{}(m).(TransactionCountByAddressWithAfterToORM); ok {
		err = posthook.AfterToORM(ctx, &to)
	}
	return to, err
}

// ToPB runs the BeforeToPB hook if present, converts the fields of this
// object to PB format, runs the AfterToPB hook, then returns the PB object
func (m *TransactionCountByAddressORM) ToPB(ctx context.Context) (TransactionCountByAddress, error) {
	to := TransactionCountByAddress{}
	var err error
	if prehook, ok := interface{}(m).(TransactionCountByAddressWithBeforeToPB); ok {
		if err = prehook.BeforeToPB(ctx, &to); err != nil {
			return to, err
		}
	}
	to.Address = m.Address
	to.TransactionHash = m.TransactionHash
	to.Count = m.Count
	if posthook, ok := interface{}(m).(TransactionCountByAddressWithAfterToPB); ok {
		err = posthook.AfterToPB(ctx, &to)
	}
	return to, err
}

// The following are interfaces you can implement for special behavior during ORM/PB conversions
// of type TransactionCountByAddress the arg will be the target, the caller the one being converted from

// TransactionCountByAddressBeforeToORM called before default ToORM code
type TransactionCountByAddressWithBeforeToORM interface {
	BeforeToORM(context.Context, *TransactionCountByAddressORM) error
}

// TransactionCountByAddressAfterToORM called after default ToORM code
type TransactionCountByAddressWithAfterToORM interface {
	AfterToORM(context.Context, *TransactionCountByAddressORM) error
}

// TransactionCountByAddressBeforeToPB called before default ToPB code
type TransactionCountByAddressWithBeforeToPB interface {
	BeforeToPB(context.Context, *TransactionCountByAddress) error
}

// TransactionCountByAddressAfterToPB called after default ToPB code
type TransactionCountByAddressWithAfterToPB interface {
	AfterToPB(context.Context, *TransactionCountByAddress) error
}

// DefaultCreateTransactionCountByAddress executes a basic gorm create call
func DefaultCreateTransactionCountByAddress(ctx context.Context, in *TransactionCountByAddress, db *gorm1.DB) (*TransactionCountByAddress, error) {
	if in == nil {
		return nil, errors1.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TransactionCountByAddressORMWithBeforeCreate_); ok {
		if db, err = hook.BeforeCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	if err = db.Create(&ormObj).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TransactionCountByAddressORMWithAfterCreate_); ok {
		if err = hook.AfterCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := ormObj.ToPB(ctx)
	return &pbResponse, err
}

type TransactionCountByAddressORMWithBeforeCreate_ interface {
	BeforeCreate_(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type TransactionCountByAddressORMWithAfterCreate_ interface {
	AfterCreate_(context.Context, *gorm1.DB) error
}

// DefaultApplyFieldMaskTransactionCountByAddress patches an pbObject with patcher according to a field mask.
func DefaultApplyFieldMaskTransactionCountByAddress(ctx context.Context, patchee *TransactionCountByAddress, patcher *TransactionCountByAddress, updateMask *field_mask1.FieldMask, prefix string, db *gorm1.DB) (*TransactionCountByAddress, error) {
	if patcher == nil {
		return nil, nil
	} else if patchee == nil {
		return nil, errors1.NilArgumentError
	}
	var err error
	for _, f := range updateMask.Paths {
		if f == prefix+"Address" {
			patchee.Address = patcher.Address
			continue
		}
		if f == prefix+"TransactionHash" {
			patchee.TransactionHash = patcher.TransactionHash
			continue
		}
		if f == prefix+"Count" {
			patchee.Count = patcher.Count
			continue
		}
	}
	if err != nil {
		return nil, err
	}
	return patchee, nil
}

// DefaultListTransactionCountByAddress executes a gorm list call
func DefaultListTransactionCountByAddress(ctx context.Context, db *gorm1.DB) ([]*TransactionCountByAddress, error) {
	in := TransactionCountByAddress{}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TransactionCountByAddressORMWithBeforeListApplyQuery); ok {
		if db, err = hook.BeforeListApplyQuery(ctx, db); err != nil {
			return nil, err
		}
	}
	db, err = gorm2.ApplyCollectionOperators(ctx, db, &TransactionCountByAddressORM{}, &TransactionCountByAddress{}, nil, nil, nil, nil)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TransactionCountByAddressORMWithBeforeListFind); ok {
		if db, err = hook.BeforeListFind(ctx, db); err != nil {
			return nil, err
		}
	}
	db = db.Where(&ormObj)
	db = db.Order("address")
	ormResponse := []TransactionCountByAddressORM{}
	if err := db.Find(&ormResponse).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TransactionCountByAddressORMWithAfterListFind); ok {
		if err = hook.AfterListFind(ctx, db, &ormResponse); err != nil {
			return nil, err
		}
	}
	pbResponse := []*TransactionCountByAddress{}
	for _, responseEntry := range ormResponse {
		temp, err := responseEntry.ToPB(ctx)
		if err != nil {
			return nil, err
		}
		pbResponse = append(pbResponse, &temp)
	}
	return pbResponse, nil
}

type TransactionCountByAddressORMWithBeforeListApplyQuery interface {
	BeforeListApplyQuery(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type TransactionCountByAddressORMWithBeforeListFind interface {
	BeforeListFind(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type TransactionCountByAddressORMWithAfterListFind interface {
	AfterListFind(context.Context, *gorm1.DB, *[]TransactionCountByAddressORM) error
}
