// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: transaction_internal_count_by_address_index.proto

package models

import (
	context "context"
	fmt "fmt"
	
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	math "math"

	gorm2 "github.com/infobloxopen/atlas-app-toolkit/gorm"
	errors1 "github.com/infobloxopen/protoc-gen-gorm/errors"
	gorm1 "github.com/jinzhu/gorm"
	field_mask1 "google.golang.org/genproto/protobuf/field_mask"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = math.Inf

type TransactionInternalCountByAddressIndexORM struct {
	Address         string `gorm:"primary_key"`
	LogIndex        uint64 `gorm:"primary_key"`
	TransactionHash string `gorm:"primary_key"`
}

// TableName overrides the default tablename generated by GORM
func (TransactionInternalCountByAddressIndexORM) TableName() string {
	return "transaction_internal_count_by_address_indices"
}

// ToORM runs the BeforeToORM hook if present, converts the fields of this
// object to ORM format, runs the AfterToORM hook, then returns the ORM object
func (m *TransactionInternalCountByAddressIndex) ToORM(ctx context.Context) (TransactionInternalCountByAddressIndexORM, error) {
	to := TransactionInternalCountByAddressIndexORM{}
	var err error
	if prehook, ok := interface{}(m).(TransactionInternalCountByAddressIndexWithBeforeToORM); ok {
		if err = prehook.BeforeToORM(ctx, &to); err != nil {
			return to, err
		}
	}
	to.TransactionHash = m.TransactionHash
	to.LogIndex = m.LogIndex
	to.Address = m.Address
	if posthook, ok := interface{}(m).(TransactionInternalCountByAddressIndexWithAfterToORM); ok {
		err = posthook.AfterToORM(ctx, &to)
	}
	return to, err
}

// ToPB runs the BeforeToPB hook if present, converts the fields of this
// object to PB format, runs the AfterToPB hook, then returns the PB object
func (m *TransactionInternalCountByAddressIndexORM) ToPB(ctx context.Context) (TransactionInternalCountByAddressIndex, error) {
	to := TransactionInternalCountByAddressIndex{}
	var err error
	if prehook, ok := interface{}(m).(TransactionInternalCountByAddressIndexWithBeforeToPB); ok {
		if err = prehook.BeforeToPB(ctx, &to); err != nil {
			return to, err
		}
	}
	to.TransactionHash = m.TransactionHash
	to.LogIndex = m.LogIndex
	to.Address = m.Address
	if posthook, ok := interface{}(m).(TransactionInternalCountByAddressIndexWithAfterToPB); ok {
		err = posthook.AfterToPB(ctx, &to)
	}
	return to, err
}

// The following are interfaces you can implement for special behavior during ORM/PB conversions
// of type TransactionInternalCountByAddressIndex the arg will be the target, the caller the one being converted from

// TransactionInternalCountByAddressIndexBeforeToORM called before default ToORM code
type TransactionInternalCountByAddressIndexWithBeforeToORM interface {
	BeforeToORM(context.Context, *TransactionInternalCountByAddressIndexORM) error
}

// TransactionInternalCountByAddressIndexAfterToORM called after default ToORM code
type TransactionInternalCountByAddressIndexWithAfterToORM interface {
	AfterToORM(context.Context, *TransactionInternalCountByAddressIndexORM) error
}

// TransactionInternalCountByAddressIndexBeforeToPB called before default ToPB code
type TransactionInternalCountByAddressIndexWithBeforeToPB interface {
	BeforeToPB(context.Context, *TransactionInternalCountByAddressIndex) error
}

// TransactionInternalCountByAddressIndexAfterToPB called after default ToPB code
type TransactionInternalCountByAddressIndexWithAfterToPB interface {
	AfterToPB(context.Context, *TransactionInternalCountByAddressIndex) error
}

// DefaultCreateTransactionInternalCountByAddressIndex executes a basic gorm create call
func DefaultCreateTransactionInternalCountByAddressIndex(ctx context.Context, in *TransactionInternalCountByAddressIndex, db *gorm1.DB) (*TransactionInternalCountByAddressIndex, error) {
	if in == nil {
		return nil, errors1.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TransactionInternalCountByAddressIndexORMWithBeforeCreate_); ok {
		if db, err = hook.BeforeCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	if err = db.Create(&ormObj).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TransactionInternalCountByAddressIndexORMWithAfterCreate_); ok {
		if err = hook.AfterCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := ormObj.ToPB(ctx)
	return &pbResponse, err
}

type TransactionInternalCountByAddressIndexORMWithBeforeCreate_ interface {
	BeforeCreate_(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type TransactionInternalCountByAddressIndexORMWithAfterCreate_ interface {
	AfterCreate_(context.Context, *gorm1.DB) error
}

// DefaultApplyFieldMaskTransactionInternalCountByAddressIndex patches an pbObject with patcher according to a field mask.
func DefaultApplyFieldMaskTransactionInternalCountByAddressIndex(ctx context.Context, patchee *TransactionInternalCountByAddressIndex, patcher *TransactionInternalCountByAddressIndex, updateMask *field_mask1.FieldMask, prefix string, db *gorm1.DB) (*TransactionInternalCountByAddressIndex, error) {
	if patcher == nil {
		return nil, nil
	} else if patchee == nil {
		return nil, errors1.NilArgumentError
	}
	var err error
	for _, f := range updateMask.Paths {
		if f == prefix+"TransactionHash" {
			patchee.TransactionHash = patcher.TransactionHash
			continue
		}
		if f == prefix+"LogIndex" {
			patchee.LogIndex = patcher.LogIndex
			continue
		}
		if f == prefix+"Address" {
			patchee.Address = patcher.Address
			continue
		}
	}
	if err != nil {
		return nil, err
	}
	return patchee, nil
}

// DefaultListTransactionInternalCountByAddressIndex executes a gorm list call
func DefaultListTransactionInternalCountByAddressIndex(ctx context.Context, db *gorm1.DB) ([]*TransactionInternalCountByAddressIndex, error) {
	in := TransactionInternalCountByAddressIndex{}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TransactionInternalCountByAddressIndexORMWithBeforeListApplyQuery); ok {
		if db, err = hook.BeforeListApplyQuery(ctx, db); err != nil {
			return nil, err
		}
	}
	db, err = gorm2.ApplyCollectionOperators(ctx, db, &TransactionInternalCountByAddressIndexORM{}, &TransactionInternalCountByAddressIndex{}, nil, nil, nil, nil)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TransactionInternalCountByAddressIndexORMWithBeforeListFind); ok {
		if db, err = hook.BeforeListFind(ctx, db); err != nil {
			return nil, err
		}
	}
	db = db.Where(&ormObj)
	db = db.Order("address")
	ormResponse := []TransactionInternalCountByAddressIndexORM{}
	if err := db.Find(&ormResponse).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TransactionInternalCountByAddressIndexORMWithAfterListFind); ok {
		if err = hook.AfterListFind(ctx, db, &ormResponse); err != nil {
			return nil, err
		}
	}
	pbResponse := []*TransactionInternalCountByAddressIndex{}
	for _, responseEntry := range ormResponse {
		temp, err := responseEntry.ToPB(ctx)
		if err != nil {
			return nil, err
		}
		pbResponse = append(pbResponse, &temp)
	}
	return pbResponse, nil
}

type TransactionInternalCountByAddressIndexORMWithBeforeListApplyQuery interface {
	BeforeListApplyQuery(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type TransactionInternalCountByAddressIndexORMWithBeforeListFind interface {
	BeforeListFind(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type TransactionInternalCountByAddressIndexORMWithAfterListFind interface {
	AfterListFind(context.Context, *gorm1.DB, *[]TransactionInternalCountByAddressIndexORM) error
}
