// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: transaction_count_by_address_index.proto

package models

import (
	context "context"
	fmt "fmt"
	
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	math "math"

	gorm2 "github.com/infobloxopen/atlas-app-toolkit/gorm"
	errors1 "github.com/infobloxopen/protoc-gen-gorm/errors"
	gorm1 "github.com/jinzhu/gorm"
	field_mask1 "google.golang.org/genproto/protobuf/field_mask"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = math.Inf

type TransactionCountByAddressIndexORM struct {
	Address         string `gorm:"primary_key"`
	BlockNumber     uint64 `gorm:"index:transaction_count_by_address_index_idx_block_number"`
	TransactionHash string `gorm:"primary_key"`
}

// TableName overrides the default tablename generated by GORM
func (TransactionCountByAddressIndexORM) TableName() string {
	return "transaction_count_by_address_indices"
}

// ToORM runs the BeforeToORM hook if present, converts the fields of this
// object to ORM format, runs the AfterToORM hook, then returns the ORM object
func (m *TransactionCountByAddressIndex) ToORM(ctx context.Context) (TransactionCountByAddressIndexORM, error) {
	to := TransactionCountByAddressIndexORM{}
	var err error
	if prehook, ok := interface{}(m).(TransactionCountByAddressIndexWithBeforeToORM); ok {
		if err = prehook.BeforeToORM(ctx, &to); err != nil {
			return to, err
		}
	}
	to.TransactionHash = m.TransactionHash
	to.Address = m.Address
	to.BlockNumber = m.BlockNumber
	if posthook, ok := interface{}(m).(TransactionCountByAddressIndexWithAfterToORM); ok {
		err = posthook.AfterToORM(ctx, &to)
	}
	return to, err
}

// ToPB runs the BeforeToPB hook if present, converts the fields of this
// object to PB format, runs the AfterToPB hook, then returns the PB object
func (m *TransactionCountByAddressIndexORM) ToPB(ctx context.Context) (TransactionCountByAddressIndex, error) {
	to := TransactionCountByAddressIndex{}
	var err error
	if prehook, ok := interface{}(m).(TransactionCountByAddressIndexWithBeforeToPB); ok {
		if err = prehook.BeforeToPB(ctx, &to); err != nil {
			return to, err
		}
	}
	to.TransactionHash = m.TransactionHash
	to.Address = m.Address
	to.BlockNumber = m.BlockNumber
	if posthook, ok := interface{}(m).(TransactionCountByAddressIndexWithAfterToPB); ok {
		err = posthook.AfterToPB(ctx, &to)
	}
	return to, err
}

// The following are interfaces you can implement for special behavior during ORM/PB conversions
// of type TransactionCountByAddressIndex the arg will be the target, the caller the one being converted from

// TransactionCountByAddressIndexBeforeToORM called before default ToORM code
type TransactionCountByAddressIndexWithBeforeToORM interface {
	BeforeToORM(context.Context, *TransactionCountByAddressIndexORM) error
}

// TransactionCountByAddressIndexAfterToORM called after default ToORM code
type TransactionCountByAddressIndexWithAfterToORM interface {
	AfterToORM(context.Context, *TransactionCountByAddressIndexORM) error
}

// TransactionCountByAddressIndexBeforeToPB called before default ToPB code
type TransactionCountByAddressIndexWithBeforeToPB interface {
	BeforeToPB(context.Context, *TransactionCountByAddressIndex) error
}

// TransactionCountByAddressIndexAfterToPB called after default ToPB code
type TransactionCountByAddressIndexWithAfterToPB interface {
	AfterToPB(context.Context, *TransactionCountByAddressIndex) error
}

// DefaultCreateTransactionCountByAddressIndex executes a basic gorm create call
func DefaultCreateTransactionCountByAddressIndex(ctx context.Context, in *TransactionCountByAddressIndex, db *gorm1.DB) (*TransactionCountByAddressIndex, error) {
	if in == nil {
		return nil, errors1.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TransactionCountByAddressIndexORMWithBeforeCreate_); ok {
		if db, err = hook.BeforeCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	if err = db.Create(&ormObj).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TransactionCountByAddressIndexORMWithAfterCreate_); ok {
		if err = hook.AfterCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := ormObj.ToPB(ctx)
	return &pbResponse, err
}

type TransactionCountByAddressIndexORMWithBeforeCreate_ interface {
	BeforeCreate_(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type TransactionCountByAddressIndexORMWithAfterCreate_ interface {
	AfterCreate_(context.Context, *gorm1.DB) error
}

// DefaultApplyFieldMaskTransactionCountByAddressIndex patches an pbObject with patcher according to a field mask.
func DefaultApplyFieldMaskTransactionCountByAddressIndex(ctx context.Context, patchee *TransactionCountByAddressIndex, patcher *TransactionCountByAddressIndex, updateMask *field_mask1.FieldMask, prefix string, db *gorm1.DB) (*TransactionCountByAddressIndex, error) {
	if patcher == nil {
		return nil, nil
	} else if patchee == nil {
		return nil, errors1.NilArgumentError
	}
	var err error
	for _, f := range updateMask.Paths {
		if f == prefix+"TransactionHash" {
			patchee.TransactionHash = patcher.TransactionHash
			continue
		}
		if f == prefix+"Address" {
			patchee.Address = patcher.Address
			continue
		}
		if f == prefix+"BlockNumber" {
			patchee.BlockNumber = patcher.BlockNumber
			continue
		}
	}
	if err != nil {
		return nil, err
	}
	return patchee, nil
}

// DefaultListTransactionCountByAddressIndex executes a gorm list call
func DefaultListTransactionCountByAddressIndex(ctx context.Context, db *gorm1.DB) ([]*TransactionCountByAddressIndex, error) {
	in := TransactionCountByAddressIndex{}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TransactionCountByAddressIndexORMWithBeforeListApplyQuery); ok {
		if db, err = hook.BeforeListApplyQuery(ctx, db); err != nil {
			return nil, err
		}
	}
	db, err = gorm2.ApplyCollectionOperators(ctx, db, &TransactionCountByAddressIndexORM{}, &TransactionCountByAddressIndex{}, nil, nil, nil, nil)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TransactionCountByAddressIndexORMWithBeforeListFind); ok {
		if db, err = hook.BeforeListFind(ctx, db); err != nil {
			return nil, err
		}
	}
	db = db.Where(&ormObj)
	db = db.Order("transaction_hash")
	ormResponse := []TransactionCountByAddressIndexORM{}
	if err := db.Find(&ormResponse).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TransactionCountByAddressIndexORMWithAfterListFind); ok {
		if err = hook.AfterListFind(ctx, db, &ormResponse); err != nil {
			return nil, err
		}
	}
	pbResponse := []*TransactionCountByAddressIndex{}
	for _, responseEntry := range ormResponse {
		temp, err := responseEntry.ToPB(ctx)
		if err != nil {
			return nil, err
		}
		pbResponse = append(pbResponse, &temp)
	}
	return pbResponse, nil
}

type TransactionCountByAddressIndexORMWithBeforeListApplyQuery interface {
	BeforeListApplyQuery(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type TransactionCountByAddressIndexORMWithBeforeListFind interface {
	BeforeListFind(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type TransactionCountByAddressIndexORMWithAfterListFind interface {
	AfterListFind(context.Context, *gorm1.DB, *[]TransactionCountByAddressIndexORM) error
}
